//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRConselho.Avaliacao.Model.Repository.ResourcesQueries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AlunoQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlunoQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BRConselho.Avaliacao.Model.Repository.ResourcesQueries.AlunoQueries", typeof(AlunoQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	Aluno.oid_pessoa as IdPessoa,
        ///		Aluno.dt_nasc_aluno as DataNascimentoAluno,
        ///		PessoaAluno.oid_pessoa as IdPessoa,
        ///		PessoaAluno.nome_pessoa as NomePessoa,
        ///		AlunoProfessor.oid_aluno as IdAluno,
        ///		AlunoProfessor.oid_professor as IdProfessor,
        ///		Professor.oid_pessoa as IdPessoa,
        ///		PessoaProfessor.oid_pessoa as IdPessoa,
        ///		PessoaProfessor.nome_pessoa as NomePessoa
        ///from	tb_aluno as Aluno
        ///inner	join tb_pessoa as PessoaAluno on Aluno.oid_pessoa = PessoaAluno.oid_pessoa
        ///inner	join tb_aluno_profess [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAlunos {
            get {
                return ResourceManager.GetString("GetAlunos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	AlunoProfessor.oid_aluno AS IdAluno,
        ///		AlunoProfessor.oid_professor AS IdProfessor,
        ///		Professor.oid_pessoa AS IdPessoa,
        ///		PessoaProfessor.oid_pessoa AS IdPessoa,
        ///		PessoaProfessor.nome_pessoa AS NomePessoa
        ///from	tb_aluno_professor AS AlunoProfessor
        ///inner	join tb_professor AS Professor on AlunoProfessor.oid_professor = Professor.oid_pessoa
        ///inner	join tb_pessoa AS PessoaProfessor on Professor.oid_pessoa = PessoaProfessor.oid_pessoa
        ///where	AlunoProfessor.oid_aluno = @IdAluno
        ///and		AlunoProfessor.o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetProfessor {
            get {
                return ResourceManager.GetString("GetProfessor", resourceCulture);
            }
        }
    }
}
